# Nifty 500 stock symbols for Yahoo Finance (NSE suffix: .NS)
# Verified June 2026 — corrected delisted/renamed tickers

NIFTY500_SYMBOLS = [
    # Large Cap — Nifty 50 core
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "BHARTIARTL.NS", "ICICIBANK.NS",
    "INFY.NS", "SBIN.NS", "HINDUNILVR.NS", "ITC.NS", "LICI.NS",
    "KOTAKBANK.NS", "LT.NS", "HCLTECH.NS", "MARUTI.NS", "BAJFINANCE.NS",
    "SUNPHARMA.NS", "ADANIENT.NS", "ONGC.NS", "TITAN.NS", "NTPC.NS",
    "AXISBANK.NS", "ULTRACEMCO.NS", "WIPRO.NS", "POWERGRID.NS", "M&M.NS",
    "ADANIPORTS.NS", "BAJAJFINSV.NS", "COALINDIA.NS", "HDFCLIFE.NS", "TECHM.NS",
    "TATASTEEL.NS", "NESTLEIND.NS", "HINDALCO.NS", "JSWSTEEL.NS", "INDUSINDBK.NS",
    "GRASIM.NS", "SBILIFE.NS", "TATACONSUM.NS", "DRREDDY.NS", "BPCL.NS",
    "BRITANNIA.NS", "CIPLA.NS", "EICHERMOT.NS", "APOLLOHOSP.NS", "DIVISLAB.NS",
    "TATAPOWER.NS", "HEROMOTOCO.NS", "BAJAJ-AUTO.NS", "ADANIGREEN.NS", "SIEMENS.NS",

    # Energy & Utilities
    "IOC.NS", "VEDL.NS", "GAIL.NS", "PETRONET.NS", "HINDPETRO.NS",
    "MRPL.NS", "CHENNPETRO.NS", "CASTROLIND.NS", "IGL.NS", "MGL.NS",
    "ATGL.NS", "CESC.NS", "TORNTPOWER.NS", "ADANIPOWER.NS",
    "NHPC.NS", "SJVN.NS", "TATAPOWER.NS",

    # IT & Technology
    "MPHASIS.NS", "COFORGE.NS", "PERSISTENT.NS", "LTIMINDTREE.NS", "LTTS.NS",
    "OFSS.NS", "KPITTECH.NS", "TATAELXSI.NS", "CYIENT.NS",
    "INTELLECT.NS", "TANLA.NS", "ROUTE.NS", "RATEGAIN.NS",
    "NAUKRI.NS", "CARTRADE.NS", "EASEMYTRIP.NS",

    # Banking & Finance
    "PNB.NS", "CANBK.NS", "FEDERALBNK.NS", "RBLBANK.NS", "KARURVYSYA.NS",
    "BANDHANBNK.NS", "CUB.NS", "DCBBANK.NS", "EQUITASBNK.NS", "UJJIVANSFB.NS",
    "BANKBARODA.NS", "YESBANK.NS", "IDFCFIRSTB.NS",
    "RECLTD.NS", "PFC.NS", "IRFC.NS", "HUDCO.NS",
    "M&MFIN.NS", "BAJAJHLDNG.NS", "LICHSGFIN.NS", "MANAPPURAM.NS", "SHRIRAMFIN.NS",
    "CHOLAFIN.NS", "MUTHOOTFIN.NS", "POONAWALLA.NS", "CREDITACC.NS",
    "HDFCAMC.NS", "NIPPONLIFE.NS", "ABCAPITAL.NS", "IIFL.NS", "360ONE.NS",
    "NUVAMA.NS", "CDSL.NS", "BSE.NS", "CAMS.NS", "KFINTECH.NS",

    # Insurance
    "ICICIPRULI.NS", "SBICARD.NS", "HDFCLIFE.NS", "SBILIFE.NS",
    "ICICIGI.NS", "GICRE.NS", "NIACL.NS", "STARHEALTH.NS", "GODIGIT.NS",

    # Pharma & Healthcare
    "LUPIN.NS", "AUROPHARMA.NS", "BIOCON.NS", "ALKEM.NS", "TORNTPHARM.NS",
    "ZYDUSLIFE.NS", "GLENMARK.NS", "IPCALAB.NS", "LAURUSLABS.NS", "NATCOPHARM.NS",
    "SANOFI.NS", "PFIZER.NS", "ABBOTINDIA.NS", "GLAXO.NS", "MANKIND.NS",
    "JBCHEPHARM.NS", "GRANULES.NS", "SUDARSCHEM.NS", "SPARC.NS", "SUVEN.NS",
    "NEULANDLAB.NS", "SHILPAMED.NS", "HERANBA.NS",
    "METROPOLIS.NS", "THYROCARE.NS", "KRSNAA.NS", "LALPATHLAB.NS",
    "APOLLOHOSP.NS", "FORTIS.NS", "MAXHEALTH.NS", "KIMS.NS",
    "ASTERDM.NS", "NH.NS", "RAINBOW.NS", "VIJAYA.NS",

    # FMCG & Consumer
    "HAVELLS.NS", "PIDILITIND.NS", "DABUR.NS", "MARICO.NS", "GODREJCP.NS",
    "COLPAL.NS", "EMAMILTD.NS", "JYOTHYLAB.NS", "PGHH.NS", "VBL.NS",
    "HATSUN.NS", "DODLA.NS", "PAGEIND.NS", "TRENT.NS",
    "RAYMOND.NS", "ARVIND.NS", "KPRMILL.NS",
    "BIKAJI.NS", "GODFRYPHLP.NS", "RADICO.NS", "UNITDSPR.NS",
    "DEVYANI.NS", "WESTLIFE.NS", "JUBLFOOD.NS",

    # Paints, Chemicals & Materials
    "ASIANPAINT.NS", "KANSAINER.NS", "BERGEPAINT.NS",
    "DEEPAKNTR.NS", "TATACHEM.NS", "GNFC.NS", "GSFC.NS",
    "COROMANDEL.NS", "CHAMBLFERT.NS", "UPL.NS", "DHANUKA.NS", "RALLIS.NS",
    "PIIND.NS", "NAVINFLUOR.NS", "FLUOROCHEM.NS", "SRF.NS",
    "ATUL.NS", "NOCIL.NS", "SOLARINDS.NS", "GHCL.NS",
    "BALAMINES.NS", "ALKYLAMINE.NS", "VINATIORGA.NS", "FINEORG.NS",
    "GALAXYSURF.NS", "SUMICHEM.NS",

    # Metals & Mining
    "NMDC.NS", "NATIONALUM.NS", "HINDCOPPER.NS", "MOIL.NS",
    "RATNAMANI.NS", "WELCORP.NS", "GPIL.NS",

    # Cement
    "AMBUJACEM.NS", "SHREECEM.NS", "ULTRACEMCO.NS", "JKCEMENT.NS",
    "HEIDELBERG.NS", "BIRLACORPN.NS", "RAMCOCEM.NS", "INDIACEM.NS",
    "MANGLMCEM.NS", "KAJARIACER.NS", "CERA.NS",

    # Real Estate
    "DLF.NS", "OBEROIRLTY.NS", "GODREJPROP.NS", "PRESTIGE.NS",
    "BRIGADE.NS", "KOLTEPATIL.NS", "PHOENIXLTD.NS", "ANANTRAJ.NS",
    "SUNTECK.NS", "SOBHA.NS", "NESCO.NS", "CAPACITE.NS",

    # Capital Goods & Infrastructure
    "BHEL.NS", "THERMAX.NS", "KEC.NS", "AIAENG.NS",
    "CUMMINSIND.NS", "ELGIEQUIP.NS", "KIRLOSENG.NS", "GREAVESCOT.NS",
    "LAXMIMACH.NS", "TDPOWERSYS.NS", "VOLTAMP.NS",
    "BEL.NS", "HAL.NS", "COCHINSHIP.NS", "MAZDOCK.NS", "GRSE.NS",
    "BEML.NS", "RVNL.NS", "RAILTEL.NS", "IRCON.NS", "NBCC.NS",
    "POWERMECH.NS", "IREDA.NS",

    # Automobiles & Auto Ancillaries
    "TVSMOTOR.NS", "ESCORTS.NS", "FORCEMOT.NS", "MAHLOG.NS",
    "APOLLOTYRE.NS", "MRF.NS", "BALKRISHNA.NS", "JKTYRE.NS",
    "SCHAEFFLER.NS", "SKFINDIA.NS", "TIMKEN.NS", "GRINDWELL.NS",
    "BHARATFORG.NS", "SONACOMS.NS", "ENDURANCE.NS", "SUPRAJIT.NS",
    "CRAFTSMAN.NS", "GABRIEL.NS", "SUNDRMFAST.NS", "SUBROS.NS",
    "EXIDEIND.NS", "LUMAXIND.NS", "VARROC.NS", "MOTHERSON.NS",

    # Consumer Durables & Electronics
    "VOLTAS.NS", "BLUESTARCO.NS", "CROMPTON.NS", "VGUARD.NS",
    "SYMPHONY.NS", "BAJAJELEC.NS", "ORIENTELEC.NS",
    "DIXON.NS", "AMBER.NS", "KAYNES.NS", "SYRMA.NS",

    # Logistics & Transport
    "CONCOR.NS", "BLUEDART.NS", "ALLCARGO.NS", "GESHIP.NS",
    "DELHIVERY.NS", "INDIGO.NS",

    # New-age / Digital
    "ZOMATO.NS", "NYKAA.NS", "PAYTM.NS", "POLICYBZR.NS",
    "MAPMYINDIA.NS", "TATATECH.NS", "ZAGGLE.NS", "IDEAFORGE.NS",

    # Textiles
    "WELSPUNLIV.NS", "TRIDENT.NS", "VIPIND.NS",

    # Housing Finance
    "AAVAS.NS", "HOMEFIRST.NS", "CANFINHOME.NS", "APTUS.NS",

    # Cables & Electricals
    "POLYCAB.NS", "KEI.NS", "FINPIPE.NS", "FINCABLES.NS",
    "APARINDS.NS", "HAVELLS.NS",

    # Misc
    "BOSCHLTD.NS", "PAGEIND.NS", "TATACOMM.NS",
    "INDIAMART.NS", "JUSTDIAL.NS", "NAUKRI.NS",
    "IRCTC.NS", "GMRAIRPORT.NS",
    "BALRAMCHIN.NS", "RENUKA.NS", "TRIVENI.NS",
    "KRBL.NS", "LTFOODS.NS",
    "CENTURYPLY.NS", "GREENPLY.NS", "GREENPANEL.NS",
    "UFLEX.NS", "SUPREMEIND.NS", "ASTRAL.NS",
    "PIRAMALENT.NS",
]


def get_symbols():
    """Return cleaned, unique list of symbols."""
    return list(dict.fromkeys(NIFTY500_SYMBOLS))
